name: Builder
on:
  push:
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create Directory
        run: |
          sudo apt install qemu-user-static g++-arm-linux-gnueabihf kpartx aria2 tree python3-requests
          tree
          mkdir images && sudo PATH=./node_modules/.bin:$PATH ./builder --noninteractive
          #echo "Folgers in your cup."
          #touch ../images/.gitkeep
